substitutions:
  device_name: test-espidf-c6

esphome:
  name: ${device_name}
  name_add_mac_suffix: false

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_MBEDTLS_GCM_C: y
      CONFIG_MBEDTLS_CIPHER_MODE_CBC: y

wifi:
  ssid: "test"
  password: "test12345678"

logger:
  level: INFO

api:
  # Note: Decryption key not supported in ESP-IDF builds
  # encryption:
  #   key: "test_key_32_characters_long=="

ota:
  platform: esphome

uart:
  id: uart_bus
  baud_rate: 115200
  rx_pin: GPIO4
  rx_buffer_size: 1700

external_components:
  - source:
      type: local
      path: ../components
    components: [ dsmr_custom ]
    refresh: 0s

dsmr_custom:
  id: dsmr_hub
  uart_id: uart_bus
  max_telegram_length: 1700
  crc_check: true

text_sensor:
  - platform: dsmr_custom
    dsmr_custom_hub_id: dsmr_hub
    identification:
      name: "P1 Telegram Header"

sensor:
  - platform: uptime
    name: "Uptime"
